
version: "3"
services:
  pgadmin:
    # 사용할 이미지
    image: dpage/pgadmin4:snapshot
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너명 설정
    container_name: pgadmin4
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "5050:80"
    # 환경 변수 설정
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    # 볼륨 설정
    volumes:
      - ./data/pgadmin/:/var/lib/pgadmin
